### ISSUE TITLE
`chain_id` checking may be too strict

### ISSUE THREAD

**Issue by en** [octopus-network/near-ibc#9]
[related tx](https://explorer.testnet.near.org/transactions/BMZ83MpLTUJMYw2mseubimZ5H8VcPPZEHnUn256cpNPb)
ContextError(ClientError(ClientSpecific { description: "StringTracer: error converting message type into domain type: invalid identifier: `identifier `ibc2` must only contain alphanumeric characters or `.`, `_`, `+`, `-`, `#`, - `[`, `]`, `<`, `>``" }))

There are some examples of valid chain_ids
https://www.mintscan.io/visualization/ibc-network

**Comment by lesterli** [comment]
For EVM-based chain, e.g OttoChain, the `chain_id` is based on the regex `^([a-z]{1,})_{1}([1-9][0-9]*)-{1}([1-9][0-9]*)$` which is from [the Evmos codes](https://github.com/octopus-network/evmos/blob/v14-otto/types/chain_id.go#L14-L35).

**Comment by DaviRain-Su** [comment]
generate chain id `ibc2` is not valid, look this 
- ibc-rs : https://github.com/cosmos/ibc-rs/blob/a2d10f1d15736f80eff56cb85a1996a20989c47f/crates/ibc/src/core/ics24_host/identifier.rs#L536 
- ibc-go: https://github.com/cosmos/ibc-go/blob/eb1892a4e7a490453fbc495f764ae0329c12fa0b/modules/core/02-client/types/height.go#L172
